- condition_name: text-embedding-ada-002
  embedding_model: text-embedding-ada-002
  chunk_size: 2048
  limit: 100
- condition_name: text-embedding-3-small
  embedding_model: text-embedding-3-small
  chunk_size: 2048
  limit: 100
- condition_name: text-embedding-3-large
  embedding_model: text-embedding-3-large
  chunk_size: 2048
  limit: 100
