- condition_name: with_reranker
  embedding_model: text-embedding-3-small
  rerank: true
  chunk_size: 2048
  limit: 100
- condition_name: without_reranker
  embedding_model: text-embedding-3-small
  rerank: false
  chunk_size: 2048
  limit: 100
