- condition_name: similarity-get20-top3
  search_type: similarity
  num_retrieved_docs: 20
  num_docs_final: 3
- condition_name: similarity-get20-top5
  search_type: similarity
  num_retrieved_docs: 20
  num_docs_final: 5
- condition_name: similarity-get20-top10
  search_type: similarity
  num_retrieved_docs: 20
  num_docs_final: 10
- condition_name: mmr-get20-top3
  search_type: mmr
  num_retrieved_docs: 20
  num_docs_final: 3
- condition_name: mmr-get20-top5
  search_type: mmr
  num_retrieved_docs: 20
  num_docs_final: 5
- condition_name: mmr-get20-top10
  search_type: mmr
  num_retrieved_docs: 20
  num_docs_final: 10
