- condition_name: character
  rag_config:
    splitter: character
    chunk_size: 2048
    limit: 100
- condition_name: recursive
  rag_config:
    splitter: recursive
    chunk_size: 2048
    limit: 100
